### ISSUE TITLE
Hintergrundbild

### ISSUE THREAD

**Issue by Skilecto** [BWSuDrive/uDrive.Frontend#4]
Für den Login-Screen, sowie die Menu Leiste bei den Benutzern wollen wir eine Art Karte haben, die wie die Straßen rund um die BWS aussehen (Beispiel aus Unterricht vom 11.09.2023)

**Comment by CuzImLloyd** [comment]
Wird parallel mit #16 bearbeitet

**Comment by CuzImLloyd** [comment]
Erledigt
